name: vanakkam

on: 
  push:
    branches:
      - main
  workflow_dispatch: 
      
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: one
        run: |
          echo "hi naavandhu one solanum "
          echo "aprem solren"
          echo "idhu push settings"
          echo " idhu path mode la py files upload panadhuku aprem vara command"
  second_job:
    runs-on: ubuntu-latest
    env:
      github_context: ${{ toJson(github) }}
    steps:
      - name: contexts fetching
        run: |
          echo "$github_context"
  third_job:
    runs-on: ubuntu-latest
    steps:
      - name: nested contexts fetching
        run: |
          echo "${{ github.event }}"
        
