name: vanakkam

on: 
  push:
    branches:
      - main
    paths:
      - '**.py'
      
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: one
        run: |
          echo "hi naavandhu one solanum "
          echo "aprem solren"
          echo "idhu push settings"
          echo " idhu path mode la py files upload panadhuku aprem vara command"
